language: java

services:
  - postgresql

before_script:
  - psql -c 'create database settlers;' -U postgres
  - psql settlers -af src/main/sql/create.sql -U postgres

after_script:
  - psql -c 'drop database settlers;' -U postgres

after_success:
  - ./gradlew jacocoTestReport coveralls
